-- MySQL Script generated by MySQL Workbench
-- Fri Feb  3 10:53:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema discostyle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema discostyle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `discostyle` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `discostyle` ;

-- -----------------------------------------------------
-- Table `discostyle`.`vinyles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `discostyle`.`vinyles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pictures` VARCHAR(255) NULL,
  `titre` VARCHAR(255) NULL,
  `genre` VARCHAR(255) NULL,
  `level_troc` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discostyle`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `discostyle`.`track` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NULL,
  `youtube_url` VARCHAR(255) NULL,
  `id_vinyles` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_track_vinyles`
    FOREIGN KEY (`id_vinyles`)
    REFERENCES `discostyle`.`vinyles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `vinyles` (`id`, `pictures`, `titre`, `genre`, `level_troc`) VALUES
(1, 'https://i.discogs.com/JVtYto3PpCrhttx7V3aR09GKcOlPw4SE8RYrdxaWPTk/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Mzc0/OS0xMTg1MTM0MTM1/LmpwZWc.jpeg', 'Enter The Wu-Tang', 'Hip Hop', 3),
(3, 'https://i.discogs.com/f7EAnCeeEn29jOEQAHmHc9sTBfU0eP1JOq2OfPu78lc/rs:fit/g:sm/q:90/h:365/w:370/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MjA5/MDgtMTMxNjM4Njg3/MC5qcGVn.jpeg', '2Pacalypse Now', 'Hip Hop', 3),
(4, 'https://i.discogs.com/K-A2Dz8a32sH7DP3pbnNj7k1lh0MnxrLWSnJvq53CGw/rs:fit/g:sm/q:90/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MjM0/MjEtMTMwNzQ4NDM4/Ny5qcGVn.jpeg', 'Naughty By Nature–Hip Hop Hooray', 'Hip Hop', 4),
(5, 'https://i.discogs.com/qQKhEwJ13YbnVcVtoY0XsOpa53Y-HYjcBhMmp36JAdo/rs:fit/g:sm/q:90/h:471/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg2MjMy/OS0xMzc3NDUxMjIy/LTY1NzAuanBlZw.jpeg', 'Nas–Hip-Hop Is Dead\r\n', 'Hip Hop', 4),
(6, 'https://i.discogs.com/Uqf1Wa_MJVWDFBpCYjVPj4WURR51zbhFY94oJygAx1s/rs:fit/g:sm/q:90/h:590/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1MDg1/NC0xMjExMDEzNDk1/LmpwZWc.jpeg', 'ABBA–More ABBA Gold', 'POP', 5),
(7, 'https://i.discogs.com/0lcNgX12vL8VIkk6JU5FM4UEdJFqSvQxiy57wXIgrNU/rs:fit/g:sm/q:90/h:639/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTI1NTY4/MC0xNDIzODc4MzU1/LTk4NzAuanBlZw.jpeg', 'Eagles-album', 'country-rock', 4),
(8, 'https://i.discogs.com/_DLW50WKZOfLBL2kS1PXCm86PLkwqA1NGIRPCjsD1lY/rs:fit/g:sm/q:90/h:514/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTIxNzY0/LTE0NDQwNTE3NTgt/NzIxMS5qcGVn.jpeg', 'Bob Marley & The Wailers', 'Jamaican reggae\r\n', 2),
(9, 'https://i.discogs.com/GzTf1lNULQliJsrzGEqdrfteTm_bHTXkbRgxMQ0g3wo/rs:fit/g:sm/q:90/h:500/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTY2MjYx/MTctMTU0MTQ0MTkx/Ny05MjI2LmpwZWc.jpeg', 'The Marvelettes', 'Soul', 3),
(10, 'https://i.discogs.com/b9ch7xQef1jb_Z1_qGucruERqTOX-WO0PRF6VuDpsrk/rs:fit/g:sm/q:90/h:591/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQzODk3/OTMtMTM2MzYxMDQy/MC01NTczLmpwZWc.jpeg', 'Various', 'Funk /Soul,Pop', 5),
(11, 'https://i.discogs.com/5UptgPU6bz8iehgGFx_5HSVkm1TEWmie8XNm2A05Bb4/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyNjAz/OTYwLTE1Mzg0MjM1/OTgtNDM0My5qcGVn.jpeg', 'Stevie Wonder', 'Funk/Soul', 3);
